AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge Backend

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:
  VisitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor_count
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitorCounter
      CodeUri: visitor_function/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  VisitorApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitorCounterApi
      CodeUri: visitor_function/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: GET

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
